import React, { useEffect, useState, useRef, useCallback } from 'react';
import { useParams } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { ChevronLeft, ChevronRight, Maximize, Minimize, Loader2 } from 'lucide-react';

// ─────────────────────────────────────────────────────────────
// PRESO — renders an HTML presentation from Supabase by UUID.
// HTML is generated by Claude Opus and stored in the
// `presentations` table. Each <section class="slide"> within the
// fetched document becomes a slide; we navigate between them
// with keyboard, button, or swipe.
// ─────────────────────────────────────────────────────────────

export default function Preso() {
  const { id } = useParams();
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);
  const [loading, setLoading] = useState(true);
  const [slides, setSlides] = useState([]);
  const [idx, setIdx] = useState(0);
  const [fullscreen, setFullscreen] = useState(false);
  const containerRef = useRef(null);

  // Fetch presentation
  useEffect(() => {
    let cancelled = false;
    (async () => {
      try {
        const res = await fetch(`/api/agentik-presentation/${id}`);
        if (!res.ok) throw new Error(res.status === 404 ? 'Presentasjonen ble ikke funnet' : 'Kunne ikke laste');
        const json = await res.json();
        if (cancelled) return;
        setData(json);

        // Parse the HTML and extract <section class="slide"> elements
        const parser = new DOMParser();
        const doc = parser.parseFromString(json.html, 'text/html');
        const sections = Array.from(doc.querySelectorAll('section.slide, .slide'));
        // Inline <style> tags from the doc so we can apply them too
        const styleTags = Array.from(doc.querySelectorAll('style')).map((s) => s.innerHTML).join('\n');
        setSlides(
          sections.map((s, i) => ({
            html: s.outerHTML,
            index: i,
          })),
        );
        // Inject styles into document head once
        if (styleTags) {
          const styleEl = document.createElement('style');
          styleEl.setAttribute('data-preso-styles', id);
          styleEl.innerHTML = styleTags;
          document.head.appendChild(styleEl);
          return () => {
            const existing = document.querySelector(`style[data-preso-styles="${id}"]`);
            if (existing) existing.remove();
          };
        }
      } catch (err) {
        if (!cancelled) setError(err.message);
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [id]);

  const goNext = useCallback(() => {
    setIdx((i) => Math.min(i + 1, slides.length - 1));
  }, [slides.length]);

  const goPrev = useCallback(() => {
    setIdx((i) => Math.max(i - 1, 0));
  }, []);

  // Keyboard navigation
  useEffect(() => {
    const onKey = (e) => {
      if (e.key === 'ArrowRight' || e.key === ' ' || e.key === 'PageDown') {
        e.preventDefault();
        goNext();
      } else if (e.key === 'ArrowLeft' || e.key === 'PageUp') {
        e.preventDefault();
        goPrev();
      } else if (e.key === 'f' || e.key === 'F') {
        toggleFullscreen();
      } else if (e.key === 'Escape' && fullscreen) {
        if (document.fullscreenElement) document.exitFullscreen();
      }
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [goNext, goPrev, fullscreen]);

  // Fullscreen toggle
  const toggleFullscreen = () => {
    if (!document.fullscreenElement) {
      containerRef.current?.requestFullscreen?.();
      setFullscreen(true);
    } else {
      document.exitFullscreen?.();
      setFullscreen(false);
    }
  };

  // Listen for fullscreen change so state stays in sync
  useEffect(() => {
    const onFsChange = () => setFullscreen(!!document.fullscreenElement);
    document.addEventListener('fullscreenchange', onFsChange);
    return () => document.removeEventListener('fullscreenchange', onFsChange);
  }, []);

  // Touch swipe
  const touchRef = useRef({ x: 0, y: 0 });
  const onTouchStart = (e) => {
    touchRef.current = { x: e.touches[0].clientX, y: e.touches[0].clientY };
  };
  const onTouchEnd = (e) => {
    const dx = e.changedTouches[0].clientX - touchRef.current.x;
    const dy = e.changedTouches[0].clientY - touchRef.current.y;
    if (Math.abs(dx) > 60 && Math.abs(dx) > Math.abs(dy)) {
      if (dx < 0) goNext();
      else goPrev();
    }
  };

  // ── Loading ──
  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ background: '#0f151d' }}>
        <Helmet><title>Laster presentasjon...</title></Helmet>
        <div className="flex flex-col items-center gap-4 text-[#f2ece1]/70">
          <Loader2 size={28} className="animate-spin" />
          <p className="text-sm" style={{ fontFamily: 'Manrope, sans-serif' }}>Laster presentasjon...</p>
        </div>
      </div>
    );
  }

  // ── Error ──
  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center px-6" style={{ background: '#0f151d' }}>
        <Helmet><title>Feil — Agentik</title></Helmet>
        <div className="max-w-md text-center" style={{ fontFamily: 'Manrope, sans-serif' }}>
          <p className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#c47a4a] mb-4">Feil</p>
          <h1 className="text-3xl font-semibold text-[#f2ece1] mb-3">{error}</h1>
          <p className="text-[#9aa4b2] text-sm">Sjekk lenken og prøv igjen, eller kontakt oss.</p>
        </div>
      </div>
    );
  }

  if (!slides.length) {
    return (
      <div className="min-h-screen flex items-center justify-center px-6" style={{ background: '#0f151d' }}>
        <Helmet><title>Tom presentasjon — Agentik</title></Helmet>
        <p className="text-[#f2ece1]/70" style={{ fontFamily: 'Manrope, sans-serif' }}>Presentasjonen er tom.</p>
      </div>
    );
  }

  // ── Main render ──
  const slide = slides[idx];
  const presoTitle = data?.client_company
    ? `${data.client_company} — AI-mulighet`
    : 'AI-mulighet';

  return (
    <>
      <Helmet>
        <title>{presoTitle} · Agentik</title>
        <meta name="robots" content="noindex, nofollow" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&family=Fraunces:ital,opsz,wght@0,9..144,400;1,9..144,400&family=JetBrains+Mono:wght@400;500&display=swap"
          rel="stylesheet"
        />
        <style>{`
          html, body, #root { height: 100%; }
          body { background: #0f151d; }
          .preso-stage {
            font-family: Manrope, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            color: #f2ece1;
          }
          .preso-slide-frame {
            aspect-ratio: 16 / 9;
            width: min(100%, calc(100vh * 16 / 9 - 80px));
            max-width: 1400px;
            background: #0f151d;
            border-radius: 16px;
            overflow: hidden;
            box-shadow: 0 30px 80px -20px rgba(0,0,0,0.6);
            border: 1px solid rgba(255,255,255,0.08);
          }
          .preso-slide-frame.is-fullscreen {
            border-radius: 0;
            border: 0;
            box-shadow: none;
            width: 100vw;
            max-width: none;
            height: 100vh;
            aspect-ratio: auto;
          }
          .preso-slide-frame > .slide,
          .preso-slide-frame > section.slide {
            width: 100%;
            height: 100%;
            box-sizing: border-box;
          }
        `}</style>
      </Helmet>

      <div
        ref={containerRef}
        className={`preso-stage min-h-screen flex flex-col items-center justify-center ${
          fullscreen ? 'p-0' : 'p-6 md:p-10'
        }`}
        style={{ background: '#0f151d' }}
        onTouchStart={onTouchStart}
        onTouchEnd={onTouchEnd}
      >
        {/* Header bar (hidden in fullscreen) */}
        {!fullscreen && (
          <div className="w-full max-w-[1400px] flex items-center justify-between mb-5 px-1">
            <div>
              <p className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#9aa4b2]">
                Agentik · For {data?.client_company || data?.client_name || 'kunde'}
              </p>
            </div>
            <div className="flex items-center gap-3">
              <span className="font-mono text-[11px] tabular-nums text-[#9aa4b2]">
                {idx + 1} / {slides.length}
              </span>
              <button
                onClick={toggleFullscreen}
                aria-label="Toggle fullscreen"
                className="p-2 rounded-lg text-[#9aa4b2] hover:text-[#f2ece1] hover:bg-white/5 transition-colors"
              >
                <Maximize size={16} />
              </button>
            </div>
          </div>
        )}

        {/* Slide */}
        <div
          className={`preso-slide-frame ${fullscreen ? 'is-fullscreen' : ''}`}
          dangerouslySetInnerHTML={{ __html: slide.html }}
          key={slide.index}
        />

        {/* Navigation (hidden in fullscreen — keyboard or swipe instead) */}
        {!fullscreen && (
          <div className="w-full max-w-[1400px] mt-5 flex items-center justify-between px-1">
            <button
              onClick={goPrev}
              disabled={idx === 0}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-white/15 text-[#f2ece1]/75 hover:text-[#f2ece1] hover:border-white/30 transition-colors disabled:opacity-30 disabled:cursor-not-allowed text-sm"
            >
              <ChevronLeft size={16} /> Forrige
            </button>
            <p className="font-mono text-[10px] uppercase tracking-[0.18em] text-[#9aa4b2]/60 hidden md:block">
              ← / → · F for fullskjerm
            </p>
            <button
              onClick={goNext}
              disabled={idx === slides.length - 1}
              className="inline-flex items-center gap-2 px-5 py-2 rounded-full bg-[#c47a4a] text-white hover:bg-[#d18d5e] transition-colors disabled:opacity-40 disabled:cursor-not-allowed text-sm font-medium"
            >
              Neste <ChevronRight size={16} />
            </button>
          </div>
        )}

        {/* Fullscreen exit hint */}
        {fullscreen && (
          <button
            onClick={toggleFullscreen}
            aria-label="Avslutt fullskjerm"
            className="fixed top-5 right-5 p-2.5 rounded-full bg-black/40 backdrop-blur text-[#f2ece1]/60 hover:text-[#f2ece1] transition-colors z-50"
          >
            <Minimize size={16} />
          </button>
        )}
      </div>
    </>
  );
}
