// POST /api/agentik-admin/onboarding
// Admin creates a new onboarding record + returns the URL to send the customer.
// This is the minimum-viable "onboard new partner" flow — no PandaDoc/Signere yet.
// Once contract signing is wired up, this endpoint will trigger the contract send instead.

import { requireAdmin, getSupabase } from '../_lib/auth.js';

const VERCEL_URL = process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'https://agentik.no';

export default async function handler(req, res) {
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' });

  let user;
  try {
    user = await requireAdmin(req);
  } catch (err) {
    return res.status(err.status || 500).json({ error: err.message });
  }

  const {
    bedrift,
    daglig_leder,
    daglig_leder_epost,
    daglig_leder_telefon,
    bedrift_domene,
    org_nr,
    pris_per_mnd,
    intern_kommentar,
    loom_video_url,
  } = req.body || {};

  if (!bedrift || !daglig_leder_epost) {
    return res.status(400).json({ error: 'bedrift og daglig_leder_epost er påkrevd' });
  }

  try {
    const supabase = getSupabase();

    // Create onboarding row — token auto-generated by DB default.
    const { data, error } = await supabase
      .from('onboardings')
      .insert({
        status: 'initiated',
        bedrift: bedrift.trim(),
        bedrift_domene: bedrift_domene?.trim() || null,
        org_nr: org_nr?.trim() || null,
        daglig_leder: daglig_leder?.trim() || null,
        daglig_leder_epost: daglig_leder_epost.trim().toLowerCase(),
        daglig_leder_telefon: daglig_leder_telefon?.trim() || null,
        pris_per_mnd: pris_per_mnd ? Number(pris_per_mnd) : 39000,
        intern_kommentar: intern_kommentar?.trim() || null,
        loom_video_url: loom_video_url?.trim() || null,
        created_by: user.email,
      })
      .select('id, token, bedrift, daglig_leder_epost')
      .single();

    if (error || !data) {
      console.error('Onboarding insert failed:', error);
      return res.status(500).json({ error: 'Kunne ikke opprette onboarding' });
    }

    return res.status(201).json({
      onboarding: data,
      url: `${VERCEL_URL}/onboarding/${data.token}`,
    });
  } catch (err) {
    console.error('Admin onboarding create error:', err);
    return res.status(500).json({ error: 'Server error' });
  }
}
